USE forkcast;

INSERT INTO recipes
(name, description, ingredients, preparation_steps, preparation_tips, nutritional_benefits, tags, calories, protein, carbs, fat, prep_time, meal_type, diet_type, difficulty, cuisine, health_goals, allergies, estimated_cost, servings, image_url)

VALUES

('Paneer Tikka',
'Grilled paneer cubes marinated with yogurt and spices.',
'Paneer,Yogurt,Ginger Garlic Paste,Red Chilli Powder,Turmeric,Garam Masala,Lemon Juice,Capsicum,Onion',
'Mix marinade. Coat paneer. Rest for 30 minutes. Skewer with vegetables. Grill for 15 minutes. Serve hot.',
'Use thick yogurt. Do not overcook paneer.',
'High protein, Rich in calcium',
'high-protein,indian,dinner,gym-friendly',
420,
28,
18,
24,
30,
'DINNER',
'VEGETARIAN',
'EASY',
'Indian',
'Muscle Gain',
'milk',
'MODERATE',
2,
'https://picsum.photos/400?1'),

('Vegetable Poha',
'Light Indian breakfast made with flattened rice and vegetables.',
'Poha,Onion,Mustard Seeds,Curry Leaves,Green Peas,Turmeric,Lemon',
'Wash poha. Saute spices and onions. Add vegetables. Mix poha. Cook 5 minutes.',
'Do not soak poha for long.',
'Good source of carbohydrates and fiber',
'breakfast,quick,budget',
280,
6,
48,
5,
20,
'BREAKFAST',
'VEGETARIAN',
'EASY',
'Indian',
'Weight Loss',
'none',
'BUDGET',
1,
'https://picsum.photos/400?2'),

('Greek Yogurt Bowl',
'Greek yogurt served with fruits and nuts.',
'Greek Yogurt,Banana,Blueberries,Almonds,Chia Seeds,Honey',
'Add yogurt to bowl. Top with fruits and nuts.',
'Use fresh fruits.',
'High protein, Rich in probiotics',
'breakfast,healthy,protein',
350,
22,
35,
10,
10,
'BREAKFAST',
'VEGETARIAN',
'EASY',
'Mediterranean',
'Weight Loss',
'milk,nuts',
'MODERATE',
1,
'https://picsum.photos/400?3');u